<?php
/**
 * Date: 22.04.16
 * Time: 21:42
 * Purpose of this class: easy applying mail templates
 * At these moment mail templates are stored in /tpl/stdstyle/email
 */

namespace Utils\Email;
use lib\Objects\OcConfig\OcConfig;


class EmailFormatter {
    private $emailContent;

    public function __construct($emailTemplateFile, $autoLoadTranslations=false) {

        $this->emailContent = $emailContent = file_get_contents($emailTemplateFile);

        if($autoLoadTranslations){
            $this->loadTranslations();
        }
    }

    //TODO: maybe prepare exactly the same mechanism like tpl_set_var... etc.
    public function setVariable($variable, $value) {
        $this->emailContent = mb_ereg_replace("{".$variable."}", $value, $this->emailContent);
    }

    public function getEmailContent()
    {
        return $this->emailContent;
    }

    /**
     * @param $username //because we always write to somebody with oc nick
     * @param bool $autoGenerated //if you don't want to add 'mail_auto_generated' text into footer - set it to false
     */
    public function addFooterAndHeader($username, $autoGenerated=true) {
        $footer = new EmailFormatter(__DIR__ . "/../../tpl/stdstyle/email/utils/ocFooter.email.html");
        $header = new EmailFormatter(__DIR__ . "/../../tpl/stdstyle/email/utils/ocHeader.email.html");

        $footer->setVariable("octeamEmailsSignature", OcConfig::getOcteamEmailsSignature());

        if($autoGenerated) {
            $footer->setVariable("mail_auto_generated", tr("mail_auto_generated"));
        } else {
            $footer->setVariable("mail_auto_generated", tr("mail_replyAllowed"));
        }

        $header->setVariable("server", OcConfig::getAbsolute_server_URI());
        $header->setVariable("oc_logo", OcConfig::getHeaderLogo());
        $header->setVariable("sitename", OcConfig::getSiteName());
        $header->setVariable("short_sitename", OcConfig::getShortSiteName());
        $header->setVariable("mail_header_hi", tr("mail_header_hi"));
        $header->setVariable("user", $username);

        $this->emailContent = $header->getEmailContent() . $this->emailContent . $footer->getEmailContent();
    }

    /**
     * this method provide translation in email templates
     * It looks for {{transl_key}} phases and replace it to proper translation string
     */
    private function loadTranslations()
    {
        if( preg_match_all("/{{[^}]*}}/u", $this->emailContent, $matches) ){

            foreach($matches[0] as $translationPhase){
                $translationKey = substr($translationPhase, 2, -2);
                $this->emailContent = preg_replace("/$translationPhase/u", tr($translationKey), $this->emailContent);
            }
        }
    }

}
