#!/bin/sh

LOGDIR=/home/ocpl/logs

# Usage: do_copy_one_log log-base-name
do_copy_one_log() {

	logname="$1.1"
	logdate=`date +%Y%m%d`
	newlogpath="$LOGDIR/$1.$logdate.gz"

	cp /var/log/apache2/$logname $LOGDIR
	gzip $LOGDIR/$logname
	mv $LOGDIR/$logname.gz $newlogpath
	chown ocpl:ocpl $newlogpath
	chmod 644 $newlogpath

}

do_copy_one_log ocpl-access.log
do_copy_one_log forum-access.log
do_copy_one_log wiki-access.log

