<table class="content">
    <colgroup><col width="100"></colgroup>
    <tr><td width=750 class="content2-pagetitle">
            <img src="tpl/stdstyle/images/blue/about.png" class="icon32" alt="OC" title="Historia OC PL" align="middle" />
            <font size="4">  <b>Historia OpenCaching PL</b></font></td></tr>

    <tr><td class="spacer"></td></tr>

</table>
<div class="searchdiv">
    <p>Moja przygoda z geocaching rozpoczęła się wiosną 2006 roku, kiedy to kupiłem Gramina 60CSx z myślą do wykorzystania go w wycieczkach rowerowych i do tworzenia własnych map topograficznych ( &quot;Toruń i okolice&quot;). Przy okazji poznawania możliwości GPS&#39;a znalazłem opcje geocaching i zainteresowałem się do czego to jest. Okazało się że geocaching to świetna sprawa w połączeniu z wyprawami rowerowymi. I tak szukając trafiłem najpierw na forum <a href="http://garmin.pl" rel="nofollow">garmin.pl</a> a p&oacute;źniej na forum strony <a href="http://www.geocache.pl" rel="nofollow">http://www.geocache.pl</a> (obecnie już nie istnieje).<br />
        Część os&oacute;b zajmujących się wtedy geocaching (była to nieliczna grupka) publikowała swoje skrzynki opr&oacute;cz <a  href="http://gpsgames.org" rel="nofollow">gpsgames.org</a> i <a href="http://geocaching.com" rel="nofollow">geocaching.com</a> także na forum aby w ten spos&oacute;b zachęcić innych z forum do szukania skrzynek. Przyszedł mi wtedy do głowy pomysł aby utworzyć lokalną bazę danych skrzynek i tak w kwietniu 2006 na forum <a href="http://garmin.pl" rel="nofollow">garmin.pl</a> rzuciłem pomysł aby utworzyć lokalny serwisu geocaching, kt&oacute;ry miałby interfejs w języku polskim dzięki temu bardziej uda nam sie zachęcić w Polsce ludzi do geocachingu. Propozycja spotkała się trochę z chłodnym przyjęciem ale mimo tego w wyniku dalszych poszukiwań okazało się że na świecie jest kilka stron mających własne bazy geocache <a  href="http://navicache.com" rel="nofollow">navicache.com</a>, <a  href="http://gpsgames.org" rel="nofollow">gpsgames.org</a>, <a href="http://terracaching.com" rel="nofollow">terracaching.com</a> oraz inne regionalne bazy geocache i tak trafiłem na projekt OpenCaching, kt&oacute;ry stał się podwaliną obecnego OpenCaching PL. Rozmawiałem z Wojtas&#39;em wtedy administrator strony <a  href="http://www.geocache.pl" rel="nofollow">http://www.geocache.pl</a> co on sądzi o tym pomyśle, on powiedział ze popiera m&oacute;j pomysł i że będę m&oacute;gł go uruchomić na serwerze <a href="http://www.geocache.pl" rel="nofollow">http://www.geocache.pl</a>. Wojtas wykupił domene <a  href="http://opencaching.pl" rel="nofollow">opencaching.pl</a> kt&oacute;ra miała posłużyć do uruchomienia przyszłego OC PL. Zabrałem się więc do pracy nad projektem i po miesięcznej pracy wprowadzania zmian i własnych usprawnień w stosunku do kodu kt&oacute;ry otrzymałem (oraz przy sporej pomocy gł&oacute;wnego developera kodu OC DE Oliver&#39;a ) oraz test&oacute;w wsp&oacute;lnie z grupą paru os&oacute;b kt&oacute;re uznały że warto spr&oacute;bować 25 maja 2006 uruchomiłem oficjalnie <a href="http://www.opencaching.pl" rel="nofollow">http://www.opencaching.pl</a></p>
</p>
<p>
    I tak oto rozpoczęła się historia OC PL. Pierwszą skrzynkę OP0001 zarejestrował Andrzej Skibicki kt&oacute;ry dużo pomagał mi w pracach testowych i wspierał mnie w tym projekcie. Z czasem wpadłem na pomysł aby wykorzystać MediaWIKI do tworzenia bazy informacji w języku polskim o geocaching i tak powstał OpenGeoWiki <a href="http://wiki.opencaching.pl" rel="nofollow">http://wiki.opencaching.pl</a> kt&oacute;ry jest tworzony przez społeczność geocacherow choc warto rozważyć przejście na system kt&oacute;ry uruchomiłem testowo na <a href="http://info.opencaching.pl" title="http://info.opencaching.pl">http://info.opencaching.pl</a> kt&oacute;ry wydaje się byc bardziej atrakckcyjny niż mediawiki.<br />
    Pierwsze 2 lata prowadziłem serwis sam. Dość&nbsp; dużo udało mi się wprowadzić nowych użytecznych funkcji w kodzie. Serwis stawał się coraz bardziej popularny i coraz więcej ludzi przybywało na OC PL co można zobaczyć na wykresie <a href="http://opencaching.pl/graphs/new-caches-oc.php" rel="nofollow">http://opencaching.pl/graphs/new-caches-oc.php</a> . Po roku działalności na wiosnę 2007 musiałem przenieść serwer OC PL z serwera gdzie był <a href="http://www.geocache.pl" rel="nofollow">http://www.geocache.pl</a> gdyż nowa wersja OC PL wymagała nowszych wersji bazy sql. Przeniosłem więc OC PL na zaprzyjaźniony serwer w firmie. W drugiej połowie 2007 upada strona <a href="http://www.geocache.pl" rel="nofollow">http://www.geocache.pl</a> a z nią nasze forum na kt&oacute;rym byliśmy. Zaczęliśmy szukać miejsca gdzie moglibyśmy komunikować się. Serwis <a href="http://www.garniak.pl" rel="nofollow">http://www.garniak.pl</a> dal nam dział poświęcony <a href="http://opencaching.pl" rel="nofollow">opencaching.pl</a> gdyż wielu ludzi z tego środowiska bawiło się w geocaching więc zn&oacute;w mieliśmy forum do komunikacji ale problem został. Zaczęliśmy wsp&oacute;lnie szukać nowego miejsca dla OC PL i wczesną wiosną 2008 OC PL znajduje swoje miejsce na stronach <a  href="http://iq.pl" rel="nofollow">iq.pl</a> gdzie do dziś serwer pracuje <a  href="http://www2.garniak.pl/viewtopic.php?f=11&amp;t=1864" rel="nofollow">http://www2.garniak.pl/viewtopic.php?f=11&amp;t=1864</a>.&nbsp; Przybywało spraw i problem&oacute;w do rozwiązania na poziomie programistycznym, zwr&oacute;ciłem się więc na forum wiosną 2008 z prośbą o pomoc <a href="http://www2.garniak.pl/viewtopic.php?f=11&amp;t=1901" rel="nofollow">http://www2.garniak.pl/viewtopic.php?f=11&amp;t=1901</a> w prowadzeniu serwisu. Po długich dyskusjach na forum nad kształtem pomocy, powstał OC Team kt&oacute;ry wsp&oacute;lnymi siłami prowadzi cały serwis od strony obsługi zgłoszeń, problem&oacute;w zgłaszanych przez użytkownik&oacute;w poprzez obsługę techniczna serwisu.<br />
    Dzięki Krzysztofowi &quot;trojmiasto&quot; kt&oacute;ry dołączył do OC Team serwis ruszył mocno z nowymi rozwiązaniami w OC PL i dzięki jego pomysłowi oraz razem wsp&oacute;lnie z Damianem &quot;rushcore&quot; w przez ponad 2 tygodnie intensywnej pracy na kodem powstał nowy wygląd OC PL i nowe funkcjonalności&nbsp; kt&oacute;ry uruchomiliśmy w grudniu 2009.<br />
    W 2011 do zespołu OC Pl dołączył Wojtek &quot;wrygiel&quot; i dzięki niemu OC PL otrzymał nowe możliwości poprzez OC PL API nazwane OKAPI <a href="http://opencaching.pl/okapi" rel="nofollow">http://opencaching.pl/okapi</a>. Duża pomoc Wojtka zaowocowała że kod OC PL stał się bardziej dostępny dla obecnych i przyszłych developer&oacute;w OC PL poprzez <a  href="https://github.com/opencaching/opencaching-pl/wiki" rel="nofollow">https://github.com/opencaching/opencaching-pl/</a>.<br />
    Stabilność serwisu od strony systemowej i technicznej&nbsp; (choć nie tylko i programistycznej w kodzie) jest dzięki Darkowi &quot;starypatyk&quot; kt&oacute;ry zawsze czuwa i działa aby system i sprzęt na kt&oacute;rym uruchomiony jest OC Pl był sprawny.</p>
<p> Jak dużo zmienił sie OC PL można por&oacute;wnać z serwisem OC CZ kt&oacute;ry nadal bazuje na wersji kodu na bazie kt&oacute;rej budowałem OC PL <a href="http://www.opencaching.cz" rel="nofollow">http://www.opencaching.cz</a>. Polska wersja bardzo mocna r&oacute;żni się od niemieckiej gdyż ludzie z środowiska OC PL starali się ciągle udoskonalać serwis aby był bardziej funkcjonalny i przyjazny dla użytkownik&oacute;w więc jest to wynik całej społeczności OC PL.</p>
<p> Uruchamiając serwis OC PL chciałem dzięki niemu spopularyzować geocaching w Polsce i to był jedyna motywacja jaka miałem tworząc OC PL. Dziś serwis ma zarejestrowanych prawie 27 000 skrzynek w tym ponad 15000 jest aktywnych i stale ich przybywa, mamy prawie 17000 os&oacute;b aktywnie bawiących się w geocaching w całej Polsce a to wszystko dzięki użytkownikom skupionych wok&oacute;ł OC PL oraz wsp&oacute;lnej pracy OC Team <a href="http://www.opencaching.pl/articles.php?page=contact" rel="nofollow">http://www.opencaching.pl/articles.php?page=contact</a> kt&oacute;ry poświęcają sw&oacute;j wolny czas aby serwis pracował sprawnie.</p>
<p> Mam nadzieje że OpenCaching.PL długo będzie jeszcze dawał możliwość zabawy w geocaching dla tych kt&oacute;rzy chcą się w to bawić.</p>
<p>
    Waldemar Ogonowski &quot;sp2ong&quot;</p>
<p>
    Grudzień 2012</p>
</p>
</div>
<p>&nbsp;</p>


