<ul><li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;06.12.2009&nbsp;<a href="viewcache.php?cacheid=8776" onmouseover="Lite('c0')" onmouseout="Lite('map')">Syn-13 Obelisk</a> założona przez <a href="viewprofile.php?userid=9981">Syn dziadka</a><br/><p class="content-title-noshade">Polska > Śląskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;06.12.2009&nbsp;<a href="viewcache.php?cacheid=8775" onmouseover="Lite('c1')" onmouseout="Lite('map')">Dwa pomniki</a> założona przez <a href="viewprofile.php?userid=4029">art_noise</a><br/><p class="content-title-noshade">Polska > Śląskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;06.12.2009&nbsp;<a href="viewcache.php?cacheid=8774" onmouseover="Lite('c2')" onmouseout="Lite('map')">Cukrownia Glinojeck - MIKOŁAJOWA SKRZYNKA ;)</a> założona przez <a href="viewprofile.php?userid=343">Hobbit</a><br/><p class="content-title-noshade">Polska > Mazowieckie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;06.12.2009&nbsp;<a href="viewcache.php?cacheid=8773" onmouseover="Lite('c3')" onmouseout="Lite('map')">Brąchnówko</a> założona przez <a href="viewprofile.php?userid=9068">Kufeld</a><br/><p class="content-title-noshade">Polska > Kujawsko-Pomorskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;06.12.2009&nbsp;<a href="viewcache.php?cacheid=8771" onmouseover="Lite('c4')" onmouseout="Lite('map')">Lubogoszcz</a> założona przez <a href="viewprofile.php?userid=7609">oszo</a><br/><p class="content-title-noshade">Polska > Małopolskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-moving.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;06.12.2009&nbsp;<a href="viewcache.php?cacheid=8770" onmouseover="Lite('c5')" onmouseout="Lite('map')">Eppendorf</a> założona przez <a href="viewprofile.php?userid=3721">MarcoPolo</a><br/><p class="content-title-noshade">Polska > Pomorskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-quiz.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;06.12.2009&nbsp;<a href="viewcache.php?cacheid=8769" onmouseover="Lite('c6')" onmouseout="Lite('map')">Czerwona Woda</a> założona przez <a href="viewprofile.php?userid=429">szym86</a><br/><p class="content-title-noshade">Polska > Kujawsko-Pomorskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;05.12.2009&nbsp;<a href="viewcache.php?cacheid=8768" onmouseover="Lite('c7')" onmouseout="Lite('map')">Głaz Niemierzyński - Wilhelma Bernharda</a> założona przez <a href="viewprofile.php?userid=7125">Boberki</a><br/><p class="content-title-noshade">Polska > Zachodniopomorskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;05.12.2009&nbsp;<a href="viewcache.php?cacheid=8767" onmouseover="Lite('c8')" onmouseout="Lite('map')">Garbarnia Temler i Szwede</a> założona przez <a href="viewprofile.php?userid=11722">maniekmaniek</a><br/><p class="content-title-noshade">Polska > Mazowieckie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;05.12.2009&nbsp;<a href="viewcache.php?cacheid=8766" onmouseover="Lite('c9')" onmouseout="Lite('map')">Głaz Barnima II</a> założona przez <a href="viewprofile.php?userid=7125">Boberki</a><br/><p class="content-title-noshade">Niemcy > Meklemburgia-Pomorze Przednie</p></li>
</ul>