<ul><li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-multi.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;30.05.2009&nbsp;<a href="viewcache.php?cacheid=6925" onmouseover="Lite('c0')" onmouseout="Lite('map')">Katastrofa Cas'y</a> założona przez <a href="viewprofile.php?userid=817">C-Yo</a><br/><p class="content-title-noshade">Polska > Zachodniopomorskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;30.05.2009&nbsp;<a href="viewcache.php?cacheid=6924" onmouseover="Lite('c1')" onmouseout="Lite('map')">Politechnika Lubelska 2/2- Dworek Rektora</a> założona przez <a href="viewprofile.php?userid=2437">lukas&amp;malgos team</a><br/><p class="content-title-noshade">Polska > Lubelskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;30.05.2009&nbsp;<a href="viewcache.php?cacheid=6923" onmouseover="Lite('c2')" onmouseout="Lite('map')">Droga Światła</a> założona przez <a href="viewprofile.php?userid=9791">Ada Królowa Świnek</a><br/><p class="content-title-noshade">Polska > Pomorskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;30.05.2009&nbsp;<a href="viewcache.php?cacheid=6922" onmouseover="Lite('c3')" onmouseout="Lite('map')">Berlinka Elbląg-Królewiec</a> założona przez <a href="viewprofile.php?userid=4800">mandrzejewski1</a><br/><p class="content-title-noshade">Polska > Warmińsko-Mazurskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;30.05.2009&nbsp;<a href="viewcache.php?cacheid=6302" onmouseover="Lite('c4')" onmouseout="Lite('map')">Las pokrzyw</a> założona przez <a href="viewprofile.php?userid=429">szym86</a><br/><p class="content-title-noshade">Polska > Kujawsko-Pomorskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;29.05.2009&nbsp;<a href="viewcache.php?cacheid=6921" onmouseover="Lite('c5')" onmouseout="Lite('map')">zaspa skm</a> założona przez <a href="viewprofile.php?userid=8500">ostry303</a><br/><p class="content-title-noshade">Polska > Pomorskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;29.05.2009&nbsp;<a href="viewcache.php?cacheid=6920" onmouseover="Lite('c6')" onmouseout="Lite('map')">G36  -&quot;Dzwonnica w Wiślinie&quot;</a> założona przez <a href="viewprofile.php?userid=7214">Giovanni</a><br/><p class="content-title-noshade">Polska > Pomorskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;29.05.2009&nbsp;<a href="viewcache.php?cacheid=6919" onmouseover="Lite('c7')" onmouseout="Lite('map')">Liszewski.36(02) - Wieża</a> założona przez <a href="viewprofile.php?userid=10379">Liszewski.36</a><br/><p class="content-title-noshade">Polska > Pomorskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;29.05.2009&nbsp;<a href="viewcache.php?cacheid=6918" onmouseover="Lite('c8')" onmouseout="Lite('map')">W Hołdzie Bohaterom</a> założona przez <a href="viewprofile.php?userid=8329">małysz</a><br/><p class="content-title-noshade">Polska > Pomorskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache" />&nbsp;29.05.2009&nbsp;<a href="viewcache.php?cacheid=6916" onmouseover="Lite('c9')" onmouseout="Lite('map')">BURZA 7 &quot;Soldatenfriedhof 1914-1918&quot;</a> założona przez <a href="viewprofile.php?userid=273">burza</a><br/><p class="content-title-noshade">Polska > Warmińsko-Mazurskie</p></li>
</ul>