<ul><li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" class="icon16" alt="Cache" title="Cache" />&nbsp;09.12.2009&nbsp;<a href="viewcache.php?cacheid=8788" onmouseover="Lite('c0')" onmouseout="Lite('map')">Krajewo - Bunkry</a> założona przez <a href="viewprofile.php?userid=10206">Konrad</a><br/><p class="content-title-noshade">Polska > Mazowieckie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-quiz.png" class="icon16" alt="Cache" title="Cache" />&nbsp;09.12.2009&nbsp;<a href="viewcache.php?cacheid=8780" onmouseover="Lite('c1')" onmouseout="Lite('map')">Śladami zaginionych uliczek</a> założona przez <a href="viewprofile.php?userid=13857">meteor2017</a><br/><p class="content-title-noshade">Polska > Mazowieckie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-quiz.png" class="icon16" alt="Cache" title="Cache" />&nbsp;08.12.2009&nbsp;<a href="viewcache.php?cacheid=8787" onmouseover="Lite('c2')" onmouseout="Lite('map')">A147 Nasze Miasto </a> założona przez <a href="viewprofile.php?userid=4502">alex22</a><br/><p class="content-title-noshade">Polska > Zachodniopomorskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-unknown.png" class="icon16" alt="Cache" title="Cache" />&nbsp;08.12.2009&nbsp;<a href="viewcache.php?cacheid=8786" onmouseover="Lite('c3')" onmouseout="Lite('map')">Powrót do przeszłości - Ostrowiec Świętokrzyski</a> założona przez <a href="viewprofile.php?userid=14626">chudzina78</a><br/><p class="content-title-noshade">Polska > Świętokrzyskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" class="icon16" alt="Cache" title="Cache" />&nbsp;08.12.2009&nbsp;<a href="viewcache.php?cacheid=8785" onmouseover="Lite('c4')" onmouseout="Lite('map')">Pomnik w Trzebiesławicach</a> założona przez <a href="viewprofile.php?userid=11021">Bracia</a><br/><p class="content-title-noshade">Polska > Śląskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-multi.png" class="icon16" alt="Cache" title="Cache" />&nbsp;08.12.2009&nbsp;<a href="viewcache.php?cacheid=8784" onmouseover="Lite('c5')" onmouseout="Lite('map')">Wyspa Piasek - lupi</a> założona przez <a href="viewprofile.php?userid=15427">lupi</a><br/><p class="content-title-noshade">Polska > Dolnośląskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-moving.png" class="icon16" alt="Cache" title="Cache" />&nbsp;08.12.2009&nbsp;<a href="viewcache.php?cacheid=8783" onmouseover="Lite('c6')" onmouseout="Lite('map')">Mikro Cwaniak 6 </a> założona przez <a href="viewprofile.php?userid=11574">survival.zhp.maggot</a><br/><p class="content-title-noshade">Polska > Pomorskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" class="icon16" alt="Cache" title="Cache" />&nbsp;08.12.2009&nbsp;<a href="viewcache.php?cacheid=8782" onmouseover="Lite('c7')" onmouseout="Lite('map')">Syn-15 POMNIK - ŻOŁNIERZA ZWYCIĘZCY</a> założona przez <a href="viewprofile.php?userid=9981">Syn dziadka</a><br/><p class="content-title-noshade">Polska > Śląskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-traditional.png" class="icon16" alt="Cache" title="Cache" />&nbsp;08.12.2009&nbsp;<a href="viewcache.php?cacheid=8781" onmouseover="Lite('c8')" onmouseout="Lite('map')">Syn-14  POMNIK - BOHATEROM ARMII CZERWONEJ</a> założona przez <a href="viewprofile.php?userid=9981">Syn dziadka</a><br/><p class="content-title-noshade">Polska > Śląskie</p></li>
<li class="newcache_list_multi" style="margin-bottom:8px;"><img src="tpl/stdstyle/images/cache/16x16-moving.png" class="icon16" alt="Cache" title="Cache" />&nbsp;08.12.2009&nbsp;<a href="viewcache.php?cacheid=8454" onmouseover="Lite('c9')" onmouseout="Lite('map')">MOBILNO-SPOTKANIOWA SKRZYNKA z Darami dla Izby Dziecka !!!</a> założona przez <a href="viewprofile.php?userid=4502">alex22</a><br/><p class="content-title-noshade">Polska > Zachodniopomorskie</p></li>
</ul>