# taken over from ddev to drop its https trailing slash redirect for directories,
# which breaks OKAPI methods like /okapi/services/caches/geocache
<VirtualHost *:80>
    SetEnvIf X-Forwarded-Proto "https" HTTPS=on

    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html
    <Directory "/var/www/html/">
        AllowOverride All
        Allow from All
    </Directory>

    ErrorLog /dev/stdout
    CustomLog ${APACHE_LOG_DIR}/access.log combined
    LimitRequestFieldSize 16380

    Alias "/phpstatus" "/var/www/phpstatus.php"
    <Location "/phpstatus">
        SetHandler "proxy:unix:/var/run/php/php-fpm.sock|fcgi://localhost"
    </Location>
    Alias "/xhprof" "/var/xhprof/xhprof_html"
    <Directory "/var/xhprof">
        Options Indexes
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:443>
    SSLEngine on
    SSLCertificateFile /etc/ssl/certs/master.crt
    SSLCertificateKeyFile /etc/ssl/certs/master.key

    SetEnvIf X-Forwarded-Proto "https" HTTPS=on

    ServerAdmin webmaster@localhost
    DocumentRoot /var/www/html
    <Directory "/var/www/html/">
        AllowOverride All
        Allow from All
    </Directory>

    ErrorLog /dev/stdout
    CustomLog ${APACHE_LOG_DIR}/access.log combined
    LimitRequestFieldSize 16380

    Alias "/phpstatus" "/var/www/phpstatus.php"
    <Location "/phpstatus">
        SetHandler "proxy:unix:/var/run/php/php-fpm.sock|fcgi://localhost"
    </Location>
    Alias "/xhprof" "/var/xhprof/xhprof_html"
    <Directory "/var/xhprof">
        Options Indexes
        AllowOverride None
        Require all granted
    </Directory>
</VirtualHost>
