# dynamic files live outside the web root on production servers
Alias /images/uploads/ /var/www/html/ocpl-dynamic-files/images/uploads/
Alias /uploads/ /var/www/html/ocpl-dynamic-files/images/uploads/
Alias /upload/ /var/www/html/ocpl-dynamic-files/images/uploads/
Alias /wigo/ /var/www/html/ocpl-dynamic-files/wigo/
Alias /download/ /var/www/html/ocpl-dynamic-files/download/
Alias /images/statpics/ /var/www/html/ocpl-dynamic-files/images/statpics/
Alias /images/mini-mapa/ /var/www/html/ocpl-dynamic-files/images/mini-mapa/
Alias /mp3/ /var/www/html/ocpl-dynamic-files/mp3/
Alias /tmp/ /var/www/html/ocpl-dynamic-files/tmp/

# unlike on production, dynamic files are inside the web root, so keep the root .htaccess router away from them
<Directory /var/www/html/ocpl-dynamic-files>
    RewriteEngine Off
</Directory>
