SET NAMES 'utf8';
DROP TABLE IF EXISTS `caches`;
CREATE TABLE IF NOT EXISTS `caches` (
  `cache_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `last_modified` datetime DEFAULT NULL,
  `date_created` datetime DEFAULT NULL,
  `type` int(11) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `country` char(2) DEFAULT NULL,
  `date_hidden` datetime DEFAULT NULL,
  `founds` int(11) DEFAULT NULL,
  `notfounds` int(11) DEFAULT NULL,
  `notes` int(11) DEFAULT NULL,
  `images` int(11) DEFAULT NULL,
  `last_found` datetime DEFAULT NULL,
  `desc_languages` varchar(60) DEFAULT NULL,
  `size` int(11) DEFAULT NULL,
  `difficulty` int(11) DEFAULT NULL,
  `terrain` int(11) DEFAULT NULL,
  `uuid` varchar(36) DEFAULT NULL,
  `watcher` int(11) DEFAULT NULL,
  `logpw` varchar(20) DEFAULT NULL,
  `picturescount` int(11) NOT NULL DEFAULT '0',
  `mp3count` int(11) NOT NULL DEFAULT '0',
  `search_time` double DEFAULT NULL,
  `way_length` double DEFAULT NULL,
  `wp_gc` varchar(7) NOT NULL COMMENT 'Geocaching.com',
  `wp_nc` varchar(6) NOT NULL COMMENT 'NaviCache',
  `wp_ge` varchar(7) NOT NULL COMMENT 'GPSGames',
  `wp_tc` varchar(7) NOT NULL COMMENT 'TerraCaching',
  `wp_oc` varchar(6) DEFAULT NULL COMMENT 'OpenCaching',
  `default_desclang` char(2) NOT NULL,
  `date_activate` datetime DEFAULT NULL,
  `topratings` int(11) NOT NULL DEFAULT '0',
  `ignorer_count` int(11) DEFAULT NULL,
  `node` tinyint(4) NOT NULL DEFAULT '0',
  `votes` int(11) NOT NULL DEFAULT '0',
  `score` float(2,1) NOT NULL DEFAULT '0.0',
  `need_npa_recalc` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`cache_id`),
  UNIQUE KEY `wp_oc` (`wp_oc`),
  KEY `longitude` (`longitude`,`latitude`),
  KEY `date_created` (`date_created`),
  KEY `latitude` (`latitude`),
  KEY `country` (`country`),
  KEY `status` (`status`,`date_activate`),
  KEY `last_modified` (`last_modified`),
  KEY `score` (`score`),
  KEY `type` (`type`),
  KEY `size` (`size`),
  KEY `difficulty` (`difficulty`),
  KEY `terrain` (`terrain`),
  KEY `name` (`name`),
  KEY `votes` (`votes`),
  KEY `picturescount` (`picturescount`),
  KEY `user_id` (`user_id`),
  KEY `need_npa_recalc` (`need_npa_recalc`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ;
