SET NAMES 'utf8';
DROP TABLE IF EXISTS `foreign_caches`;
CREATE TABLE IF NOT EXISTS `foreign_caches` (
  `cache_id` int(11) NOT NULL,
  `user_id` int(11) default NULL,
  `username` varchar(90) NOT NULL,
  `name` varchar(255) default NULL,
  `longitude` double default NULL,
  `latitude` double default NULL,
  `last_modified` datetime default NULL,
  `date_created` datetime default NULL,
  `type` int(11) default NULL,
  `status` int(11) default NULL,
  `country` char(2) default NULL,
  `date_hidden` datetime default NULL,
  `founds` int(11) default NULL,
  `notfounds` int(11) default NULL,
  `notes` int(11) default NULL,
  `images` int(11) default NULL,
  `last_found` datetime default NULL,
  `desc_languages` varchar(60) default NULL,
  `size` int(11) default NULL,
  `difficulty` int(11) default NULL,
  `terrain` int(11) default NULL,
  `uuid` varchar(36) default NULL,
  `watcher` int(11) default NULL,
  `logpw` varchar(20) default NULL,
  `picturescount` int(11) NOT NULL default '0',
  `search_time` double default NULL,
  `way_length` double default NULL,
  `wp_gc` varchar(7) NOT NULL,
  `wp_nc` varchar(6) NOT NULL,
  `wp_oc` varchar(6) default NULL,
  `default_desclang` char(2) NOT NULL,
  `date_activate` datetime default NULL,
  `topratings` int(11) NOT NULL default '0',
  `ignorer_count` int(11) default NULL,
  `node` tinyint(4) NOT NULL default '0',
  `votes` int(11) NOT NULL default '0',
  `score` float(2,1) NOT NULL default '0.0',
  PRIMARY KEY  (`cache_id`,`node`),
  UNIQUE KEY `wp_oc` (`wp_oc`),
  KEY `longitude` (`longitude`,`latitude`),
  KEY `date_created` (`date_created`),
  KEY `latitude` (`latitude`),
  KEY `country` (`country`),
  KEY `status` (`status`,`date_activate`),
  KEY `last_modified` (`last_modified`),
  KEY `user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


