SET NAMES 'utf8';
DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(60) CHARACTER SET utf8 COLLATE utf8_polish_ci DEFAULT NULL,
  `password` varchar(512) DEFAULT NULL,
  `email` varchar(60) DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `last_modified` datetime DEFAULT NULL,
  `login_faults` int(11) DEFAULT NULL,
  `last_login` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `login_id` varchar(13) DEFAULT NULL,
  `is_active_flag` int(11) DEFAULT NULL,
  `was_loggedin` int(11) DEFAULT NULL,
  `country` char(2) DEFAULT NULL,
  `pmr_flag` int(11) DEFAULT NULL,
  `new_pw_code` varchar(13) DEFAULT NULL,
  `new_pw_date` int(11) DEFAULT NULL,
  `date_created` datetime DEFAULT NULL,
  `new_email_code` varchar(13) DEFAULT NULL,
  `new_email_date` int(11) DEFAULT NULL,
  `new_email` varchar(60) DEFAULT NULL,
  `post_news` int(11) DEFAULT NULL,
  `hidden_count` int(11) DEFAULT '0',
  `log_notes_count` int(11) DEFAULT '0',
  `founds_count` int(11) DEFAULT '0',
  `notfounds_count` int(11) DEFAULT '0',
  `uuid` varchar(36) DEFAULT NULL,
  `cache_watches` int(11) DEFAULT NULL,
  `permanent_login_flag` int(11) DEFAULT NULL,
  `watchmail_mode` int(11) NOT NULL DEFAULT '1',
  `watchmail_hour` int(11) NOT NULL DEFAULT '0',
  `watchmail_nextmail` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `watchmail_day` int(11) NOT NULL DEFAULT '0',
  `activation_code` varchar(13) NOT NULL,
  `statpic_logo` int(11) NOT NULL DEFAULT '0',
  `statpic_text` varchar(30) NOT NULL DEFAULT 'Opencaching',
  `cache_ignores` int(11) DEFAULT '0',
  `no_htmledit_flag` tinyint(1) NOT NULL DEFAULT '0',
  `notify_radius` int(11) NOT NULL DEFAULT '0',
  `admin` tinyint(1) NOT NULL DEFAULT '0',
  `guru` tinyint(1) NOT NULL DEFAULT '0',
  `node` tinyint(4) NOT NULL DEFAULT '0',
  `stat_ban` tinyint(1) NOT NULL DEFAULT '0',
  `description` varchar(1024) DEFAULT NULL,
  `rules_confirmed` int(1) NOT NULL DEFAULT '0',
  `get_bulletin` tinyint(1) NOT NULL DEFAULT '1',
  `ozi_filips` varchar(255) DEFAULT NULL,
  `hide_flag` int(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `email` (`email`),
  KEY `notify_radius` (`notify_radius`),
  KEY `username` (`username`),
  KEY `hidden_count` (`hidden_count`),
  KEY `founds_count` (`founds_count`),
  KEY `notfounds_count` (`notfounds_count`),
  KEY `uuid` (`uuid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;



