
<div class="content2-pagetitle"><img src="tpl/stdstyle/images/blue/cache.png" border="0" width="32" height="32" alt="Cachesuche" title="Cache" align="middle"/>&nbsp;Najnowsze skrzynki poza Polską</div>
<div class="content2-container line-box">
    <p class="content-title-noshade-size3">Austria</p><p>29.05.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3693">Miasto... a może to morze?</a> założona przez <a href="viewprofile.php?userid=796">Kiko</a>
    </p><p>29.05.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3692">Cały Wiedeń, w jednym oku</a> założona przez <a href="viewprofile.php?userid=796">Kiko</a>
    </p><p class="content-title-noshade-size3">Belgia</p><p>20.06.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=1197">Belgijska Wierzba</a> założona przez <a href="viewprofile.php?userid=315">GeoCrak Team</a>
    </p><p class="content-title-noshade-size3">Białoruś</p><p>29.07.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=1454">ted51_Różany</a> założona przez <a href="viewprofile.php?userid=457">t_e_d</a>
    </p><p>29.07.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=1453">ted_v17_Pruzany_pomnik</a> założona przez <a href="viewprofile.php?userid=457">t_e_d</a>
    </p><p>29.07.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=1452">ted50_Pruzany_Muchawiec</a> założona przez <a href="viewprofile.php?userid=457">t_e_d</a>
    </p><p class="content-title-noshade-size3">Chorwacja</p><p>02.09.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7932">Vidova gora</a> założona przez <a href="viewprofile.php?userid=9243">marcin2wojcik</a>
    </p><p>03.07.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4050">Wymarłe miasto</a> założona przez <a href="viewprofile.php?userid=2020">Leesec &amp; Voytos</a>
    </p><p class="content-title-noshade-size3">Czeska Republika</p><p>11.02.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5790">Hronovskie źródła mineralne</a> założona przez <a href="viewprofile.php?userid=6802">amelek</a>
    </p><p>11.02.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5788">Hronov, kościół Wszystkich Świętych</a> założona przez <a href="viewprofile.php?userid=6802">amelek</a>
    </p><p>10.02.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5786">Jiraskova chata</a> założona przez <a href="viewprofile.php?userid=6802">amelek</a>
    </p><p>10.02.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5785">Zamek w Nachodzie</a> założona przez <a href="viewprofile.php?userid=6802">amelek</a>
    </p><p>10.02.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5784">Twierdza Dobrosov (Mustek)</a> założona przez <a href="viewprofile.php?userid=6802">amelek</a>
    </p><p>10.02.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5783">Cmentarz wojenny 1866</a> założona przez <a href="viewprofile.php?userid=6802">amelek</a>
    </p><p>17.11.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5382">Praga - Plac Wacława</a> założona przez <a href="viewprofile.php?userid=1554">Nina</a>
    </p><p>17.11.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5381">Praga - Střelecký ostrov</a> założona przez <a href="viewprofile.php?userid=1554">Nina</a>
    </p><p>17.11.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5380">Praga - Ogrody praskie</a> założona przez <a href="viewprofile.php?userid=1554">Nina</a>
    </p><p>17.11.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5379">Praga - Kościół św. Piotra i Pawła</a> założona przez <a href="viewprofile.php?userid=1554">Nina</a>
    </p><p>14.11.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5357">filips200: Filipka 762 (vrchol)</a> założona przez <a href="viewprofile.php?userid=49">filips</a>
    </p><p>14.11.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5354">filips197: Tajne spotkania ewangelików</a> założona przez <a href="viewprofile.php?userid=49">filips</a>
    </p><p>26.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4946">Twierdza artyleryjska Hurka</a> założona przez <a href="viewprofile.php?userid=974">Ciutnik</a>
    </p><p>25.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4943">Krizovy vrch</a> założona przez <a href="viewprofile.php?userid=974">Ciutnik</a>
    </p><p>03.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-quiz.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4740">Slovanské opevněné hradiště</a> założona przez <a href="viewprofile.php?userid=5407">krteczek</a>
    </p><p>28.08.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4665">Kovazova Rokie</a> założona przez <a href="viewprofile.php?userid=3253">Gnidus</a>
    </p><p>19.08.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4565">Janova Skala (CZ)</a> założona przez <a href="viewprofile.php?userid=3253">Gnidus</a>
    </p><p>30.07.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4281">broumovske steny / broumov walls</a> założona przez <a href="viewprofile.php?userid=1918">ladabohac</a>
    </p><p>14.07.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4144">Jezioro Piskovina</a> założona przez <a href="viewprofile.php?userid=3253">Gnidus</a>
    </p><p>14.07.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4143">Mariana</a> założona przez <a href="viewprofile.php?userid=3253">Gnidus</a>
    </p><p>27.05.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3676">Heegerova vyhlidka</a> założona przez <a href="viewprofile.php?userid=123">Redbox-PL</a>
    </p><p>17.05.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3516">Jaskinia Macochy</a> założona przez <a href="viewprofile.php?userid=796">Kiko</a>
    </p><p>17.05.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3513">Skalny Młyn</a> założona przez <a href="viewprofile.php?userid=796">Kiko</a>
    </p><p>09.04.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3119">Borówkowa</a> założona przez <a href="viewprofile.php?userid=332">robertd</a>
    </p><p>23.11.2006 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=208">PETROVY BOUDY</a> założona przez <a href="viewprofile.php?userid=123">Redbox-PL</a>
    </p><p class="content-title-noshade-size3">Dania</p><p>31.08.2009 - <img src="tpl/stdstyle/images/cache/16x16-multi.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7902">Zby. 18 - DK-Moesgard</a> założona przez <a href="viewprofile.php?userid=1499">Zby.</a>
    </p><p>31.07.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7498">Dueodde Fyr</a> założona przez <a href="viewprofile.php?userid=433">bogobig</a>
    </p><p>25.11.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5417">Pod wodą</a> założona przez <a href="viewprofile.php?userid=1291">makos</a>
    </p><p class="content-title-noshade-size3">Egipt</p><p>09.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4822">SINAIS VULTURES</a> założona przez <a href="viewprofile.php?userid=5411">sebas</a>
    </p><p>27.04.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3274">Piramidy</a> założona przez <a href="viewprofile.php?userid=801">PatrykG</a>
    </p><p class="content-title-noshade-size3">Estonia</p><p>01.08.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7525">B&amp;B10 Cmentarz Mäla</a> założona przez <a href="viewprofile.php?userid=9053">BeautyAndBeast</a>
    </p><p>01.08.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7521">B&amp;B9 Klif Pulli</a> założona przez <a href="viewprofile.php?userid=9053">BeautyAndBeast</a>
    </p><p>28.07.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7481">B&amp;B8 Forteca Maasi</a> założona przez <a href="viewprofile.php?userid=9053">BeautyAndBeast</a>
    </p><p>28.07.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7480">B&amp;B7 Zamek Põltsamaa</a> założona przez <a href="viewprofile.php?userid=9053">BeautyAndBeast</a>
    </p><p>10.07.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7326">B&amp;B6 Zapora na Väike väin</a> założona przez <a href="viewprofile.php?userid=9053">BeautyAndBeast</a>
    </p><p>09.07.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7322">B&amp;B5 Grodzisko Muhu</a> założona przez <a href="viewprofile.php?userid=9053">BeautyAndBeast</a>
    </p><p>05.07.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7288">B&amp;B4 Szczęśliwy los</a> założona przez <a href="viewprofile.php?userid=9053">BeautyAndBeast</a>
    </p><p>29.06.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7237">B&amp;B3 Wieża wodna w Rakvere</a> założona przez <a href="viewprofile.php?userid=9053">BeautyAndBeast</a>
    </p><p>29.06.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7236">Rybak</a> założona przez <a href="viewprofile.php?userid=9053">BeautyAndBeast</a>
    </p><p>28.06.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7217">B&amp;B2 Dębina Vinni-Pajusti</a> założona przez <a href="viewprofile.php?userid=9053">BeautyAndBeast</a>
    </p><p>21.05.2009 - <img src="tpl/stdstyle/images/cache/16x16-multi.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6743">B&amp;B1 Potęga pieśni</a> założona przez <a href="viewprofile.php?userid=9053">BeautyAndBeast</a>
    </p><p class="content-title-noshade-size3">Francja</p><p>25.12.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5576">Grób Chopina</a> założona przez <a href="viewprofile.php?userid=972">shchenka</a>
    </p><p>17.06.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3896">ZYR 155 - La Defence - Łuk triumfalny II</a> założona przez <a href="viewprofile.php?userid=449">ZYR</a>
    </p><p>07.06.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3765">W centrum Paryża</a> założona przez <a href="viewprofile.php?userid=960">irudzin76</a>
    </p><p>25.04.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3248">TERAZ POLSKA</a> założona przez <a href="viewprofile.php?userid=1029">Mroofki Team</a>
    </p><p>11.11.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=2250">Saulx-les-Chartreux</a> założona przez <a href="viewprofile.php?userid=1291">makos</a>
    </p><p>11.11.2007 - <img src="tpl/stdstyle/images/cache/16x16-webcam.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=2248">Luwr</a> założona przez <a href="viewprofile.php?userid=1291">makos</a>
    </p><p>10.11.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=2237">Wieża Eiffla</a> założona przez <a href="viewprofile.php?userid=1291">makos</a>
    </p><p>09.11.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=2234">Père-Lachaise</a> założona przez <a href="viewprofile.php?userid=1291">makos</a>
    </p><p>09.11.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=2232">Łuk Triumfalny</a> założona przez <a href="viewprofile.php?userid=1291">makos</a>
    </p><p>20.06.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=1195">Bunkry Śniad Skrzynka Komin</a> założona przez <a href="viewprofile.php?userid=315">GeoCrak Team</a>
    </p><p class="content-title-noshade-size3">Grecja</p><p>08.10.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=8324">Kreta - Fort wenecki</a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>08.10.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=8323">Kreta - Wąwóz Faraga</a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>08.10.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=8322">Kreta Matala </a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>08.10.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=8320">Kreta - Kalamaki hippie dream</a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>08.10.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=8318">Kreta - Palmowy las</a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>08.10.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=8317">Kreta  - Pomnik Walecznych</a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>16.08.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7690">C2_archaeological site_CYPRUS</a> założona przez <a href="viewprofile.php?userid=13318">cyprus</a>
    </p><p>14.08.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7676">C1_excavations_CYPRUS</a> założona przez <a href="viewprofile.php?userid=13318">cyprus</a>
    </p><p>14.08.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7675">Κρήτη Αλκατραζ</a> założona przez <a href="viewprofile.php?userid=58">Saracen</a>
    </p><p>13.08.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7648">Ghost Village 2</a> założona przez <a href="viewprofile.php?userid=58">Saracen</a>
    </p><p>25.07.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7455">Wąwóz Kourtaliotiko</a> założona przez <a href="viewprofile.php?userid=58">Saracen</a>
    </p><p>08.07.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7319">/Rodos/ - zatoka Anthony Quinn</a> założona przez <a href="viewprofile.php?userid=4029">art_noise</a>
    </p><p>08.07.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7318">/Rodos/ Punkt widokowy Lindos</a> założona przez <a href="viewprofile.php?userid=4029">art_noise</a>
    </p><p>08.07.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7317">/Rodos/ Rodos - punkt widokowy</a> założona przez <a href="viewprofile.php?userid=4029">art_noise</a>
    </p><p>04.06.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6978">Morska Iguana</a> założona przez <a href="viewprofile.php?userid=1380">Cofo</a>
    </p><p>04.06.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6976">Kretońska Sosna</a> założona przez <a href="viewprofile.php?userid=1380">Cofo</a>
    </p><p>31.03.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6114">Dżentelmeni</a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>24.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4933">Cypr - tombs of the kings</a> założona przez <a href="viewprofile.php?userid=4029">art_noise</a>
    </p><p>24.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4931">Cypr - Lara Reserve</a> założona przez <a href="viewprofile.php?userid=4029">art_noise</a>
    </p><p>17.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4882">Kreta - Falasarna wykopaliska</a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>17.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4881">Kreta - Falasarna 2</a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>17.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4880">Kreta - Falasarna</a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>17.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4879">Kreta - Urwisko</a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>17.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4878">Kreta - księżycowy krajobraz </a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>28.05.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3679">Elafonissos Beach</a> założona przez <a href="viewprofile.php?userid=433">bogobig</a>
    </p><p>19.06.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=1031">LYGARIA BOX</a> założona przez <a href="viewprofile.php?userid=58">Saracen</a>
    </p><p class="content-title-noshade-size3">Hiszpania</p><p>03.04.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6042">TEN 5 Sosnowy las ze snu psychopaty</a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>03.04.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6041">TEN 4 - ale tu się działo 200 lat temu !!!</a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>03.04.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6040">TEN 3 Widok na wulkan</a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>03.04.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6039">TEN 2 Wulkan</a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>23.03.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6038">TEN 1 wąwóz </a> założona przez <a href="viewprofile.php?userid=5446">Krzychu Blues</a>
    </p><p>29.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4851">filips187: Szczyt z popiersiem</a> założona przez <a href="viewprofile.php?userid=49">filips</a>
    </p><p>12.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4854">filips189: Nuria - tama</a> założona przez <a href="viewprofile.php?userid=49">filips</a>
    </p><p>12.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4852">filips188: Refugi Coma de Vaca</a> założona przez <a href="viewprofile.php?userid=49">filips</a>
    </p><p>12.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4850">filips186: Bunkier obronny jednoosobowy</a> założona przez <a href="viewprofile.php?userid=49">filips</a>
    </p><p>31.08.2006 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=118">filips25: Sierra Nevada</a> założona przez <a href="viewprofile.php?userid=49">filips</a>
    </p><p>31.08.2006 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=117">filips24: Esera Valley / Aneto</a> założona przez <a href="viewprofile.php?userid=49">filips</a>
    </p><p>31.08.2006 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=116">filips23: Ibon Llardaneta</a> założona przez <a href="viewprofile.php?userid=49">filips</a>
    </p><p class="content-title-noshade-size3">Holandia</p><p>20.06.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=1198">Evergreen</a> założona przez <a href="viewprofile.php?userid=315">GeoCrak Team</a>
    </p><p class="content-title-noshade-size3">Irlandia</p><p>08.10.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5033">Bray Head</a> założona przez <a href="viewprofile.php?userid=801">PatrykG</a>
    </p><p class="content-title-noshade-size3">Lettland</p><p>26.12.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5582">Akcja Paczka na Łotwie</a> założona przez <a href="viewprofile.php?userid=2306">stary_pop</a>
    </p><p class="content-title-noshade-size3">Litwa</p><p>19.06.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3909">ted157_Liskiava</a> założona przez <a href="viewprofile.php?userid=457">t_e_d</a>
    </p><p>18.06.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3908">ted156_zielona_granica</a> założona przez <a href="viewprofile.php?userid=457">t_e_d</a>
    </p><p>14.05.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3500">ted150_aqua_park</a> założona przez <a href="viewprofile.php?userid=457">t_e_d</a>
    </p><p>14.05.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3499">ted149_miejsce_kultu</a> założona przez <a href="viewprofile.php?userid=457">t_e_d</a>
    </p><p>14.05.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3498">ted148_za_szlabanem</a> założona przez <a href="viewprofile.php?userid=457">t_e_d</a>
    </p><p>14.05.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3495">ted_v25_E.Plater</a> założona przez <a href="viewprofile.php?userid=457">t_e_d</a>
    </p><p>07.05.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=864">filips70: Jezioro Aviris</a> założona przez <a href="viewprofile.php?userid=49">filips</a>
    </p><p>07.05.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=863">filips69: Nad Niemnem</a> założona przez <a href="viewprofile.php?userid=49">filips</a>
    </p><p>07.05.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=862">filips68: Zapomniany pomnik</a> założona przez <a href="viewprofile.php?userid=49">filips</a>
    </p><p>07.05.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=861">filips67: Stumilowy Las</a> założona przez <a href="viewprofile.php?userid=49">filips</a>
    </p><p class="content-title-noshade-size3">Monaco</p><p>08.05.2008 - <img src="tpl/stdstyle/images/cache/16x16-moving.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3418">Hazard</a> założona przez <a href="viewprofile.php?userid=1291">makos</a>
    </p><p class="content-title-noshade-size3">Myanmar</p><p>05.11.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=8511">Schloss Heerbrugg</a> założona przez <a href="viewprofile.php?userid=319">Mela</a>
    </p><p class="content-title-noshade-size3">Niemcy</p><p>30.08.2009 - <img src="tpl/stdstyle/images/cache/16x16-multi.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7876">WYZNACZNIK kierunku, czyli Pole Kopców</a> założona przez <a href="viewprofile.php?userid=9432">kaber</a>
    </p><p>27.11.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5424">U-461    Muzeum</a> założona przez <a href="viewprofile.php?userid=3627">QFerki squad</a>
    </p><p>06.10.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5019">A020- Podnośnia dla statków o wysokości 36m.</a> założona przez <a href="viewprofile.php?userid=4509">Arishia</a>
    </p><p>26.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4947">Frauenkirche - KT1</a> założona przez <a href="viewprofile.php?userid=5923">KrystianT</a>
    </p><p>25.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4945">Mercedes-Benz </a> założona przez <a href="viewprofile.php?userid=1291">makos</a>
    </p><p>15.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-webcam.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4873">E 009° 00.000'</a> założona przez <a href="viewprofile.php?userid=1291">makos</a>
    </p><p>02.08.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4316">Kozicznik 008</a> założona przez <a href="viewprofile.php?userid=2824">koziczki</a>
    </p><p>31.05.2008 - <img src="tpl/stdstyle/images/cache/16x16-quiz.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3704">LSD-1 Köln Dom</a> założona przez <a href="viewprofile.php?userid=58">Saracen</a>
    </p><p>19.03.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=2956">Kalksteinwerk</a> założona przez <a href="viewprofile.php?userid=1936">meatmanfamily</a>
    </p><p>16.09.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=1885">ZYR 69 - Ale lipa ;)</a> założona przez <a href="viewprofile.php?userid=449">ZYR</a>
    </p><p>16.09.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=1884">ZYR 68 - Domek ratownika</a> założona przez <a href="viewprofile.php?userid=449">ZYR</a>
    </p><p>16.09.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=1883">ZYR 67 - Jezioro Seeblick</a> założona przez <a href="viewprofile.php?userid=449">ZYR</a>
    </p><p>04.05.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=813">ENERGIA</a> założona przez <a href="viewprofile.php?userid=315">GeoCrak Team</a>
    </p><p>04.05.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=812">STARY MOST w GREENE</a> założona przez <a href="viewprofile.php?userid=315">GeoCrak Team</a>
    </p><p>04.05.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=807">KLON</a> założona przez <a href="viewprofile.php?userid=315">GeoCrak Team</a>
    </p><p>04.05.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=806">JA JA DAS IST PIEENIEK </a> założona przez <a href="viewprofile.php?userid=315">GeoCrak Team</a>
    </p><p>09.03.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=454">Bad Durkheim/AFW Team No-11</a> założona przez <a href="viewprofile.php?userid=12">woytas</a>
    </p><p>08.03.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=452">Targowisko na starym mieście w Monachium</a> założona przez <a href="viewprofile.php?userid=319">Mela</a>
    </p><p class="content-title-noshade-size3">Norwegia</p><p>20.05.2009 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6737">G40 - &quot;Dalej tylko Valhalla&quot;</a> założona przez <a href="viewprofile.php?userid=7214">Giovanni</a>
    </p><p>20.05.2009 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6736">G42 - &quot;Powrót do Przeszłości - Maryjny Ostrów&quot;</a> założona przez <a href="viewprofile.php?userid=7214">Giovanni</a>
    </p><p>28.02.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5876">GeoIce</a> założona przez <a href="viewprofile.php?userid=366">Kazik_174</a>
    </p><p>13.12.2008 - <img src="tpl/stdstyle/images/cache/16x16-quiz.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5531"> Myrerskogveien - Lachmanns vei (GC1J6HH)</a> założona przez <a href="viewprofile.php?userid=7019">brhel</a>
    </p><p class="content-title-noshade-size3">Portugalia</p><p>16.07.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7379">Cabo da Roca - Tam gdzie kończy się ziemia a morze zaczyna.</a> założona przez <a href="viewprofile.php?userid=9243">marcin2wojcik</a>
    </p><p class="content-title-noshade-size3">Rosja</p><p>20.05.2009 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6713">50.619621665198 sr: tak blisko, a tak daleko...</a> założona przez <a href="viewprofile.php?userid=58">Saracen</a>
    </p><p class="content-title-noshade-size3">Rumunia</p><p>11.09.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=8030">Pietros</a> założona przez <a href="viewprofile.php?userid=1933">radosny</a>
    </p><p>04.06.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6975">Góry Rodniańskie 3 Biwak</a> założona przez <a href="viewprofile.php?userid=34">Wojtek1121</a>
    </p><p>04.06.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6974">Góry Rodniańskie 2 Jeziorko</a> założona przez <a href="viewprofile.php?userid=34">Wojtek1121</a>
    </p><p>04.06.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6973">Góry Rodniańskie 1</a> założona przez <a href="viewprofile.php?userid=34">Wojtek1121</a>
    </p><p>08.04.2009 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6193">G23 - &quot;Kirlibaba, styczeń 1915&quot;</a> założona przez <a href="viewprofile.php?userid=7214">Giovanni</a>
    </p><p>07.04.2009 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6185">G22- &quot;Przełęcz Prilslop&quot;</a> założona przez <a href="viewprofile.php?userid=7214">Giovanni</a>
    </p><p>30.03.2009 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6107">G16 - &quot;Malowany monastyr  Gura Humurului&quot;</a> założona przez <a href="viewprofile.php?userid=7214">Giovanni</a>
    </p><p class="content-title-noshade-size3">Szwajcaria</p><p>22.08.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7775">Opuszczona nora</a> założona przez <a href="viewprofile.php?userid=429">szym86</a>
    </p><p>26.07.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7466">Viking treasure island</a> założona przez <a href="viewprofile.php?userid=429">szym86</a>
    </p><p>05.12.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5486">6x9</a> założona przez <a href="viewprofile.php?userid=1291">makos</a>
    </p><p>24.11.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5416">Turning Torso</a> założona przez <a href="viewprofile.php?userid=1291">makos</a>
    </p><p>24.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4932">Wielka Tama</a> założona przez <a href="viewprofile.php?userid=429">szym86</a>
    </p><p>21.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4899">Stary Port</a> założona przez <a href="viewprofile.php?userid=429">szym86</a>
    </p><p>20.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4895">Foczka</a> założona przez <a href="viewprofile.php?userid=429">szym86</a>
    </p><p>12.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4855">Podziemie</a> założona przez <a href="viewprofile.php?userid=429">szym86</a>
    </p><p>06.08.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4354">Oparty Kamień</a> założona przez <a href="viewprofile.php?userid=429">szym86</a>
    </p><p>20.07.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4194">Szlak na Ursand</a> założona przez <a href="viewprofile.php?userid=429">szym86</a>
    </p><p>20.07.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4193">Zatoka Czaszki</a> założona przez <a href="viewprofile.php?userid=429">szym86</a>
    </p><p>19.07.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4182">Magic Stone</a> założona przez <a href="viewprofile.php?userid=429">szym86</a>
    </p><p>18.07.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4180">Kamienny Mur</a> założona przez <a href="viewprofile.php?userid=429">szym86</a>
    </p><p class="content-title-noshade-size3">Szwecja</p><p>08.08.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7601">Ucieczka z Alcatraz</a> założona przez <a href="viewprofile.php?userid=429">szym86</a>
    </p><p class="content-title-noshade-size3">Słowacja</p><p>28.04.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6440">Farma Gejdak</a> założona przez <a href="viewprofile.php?userid=9076">mr_beef</a>
    </p><p>08.01.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5637">filips205: Pomnik ofiar faszyzmu w Cigel'ce</a> założona przez <a href="viewprofile.php?userid=49">filips</a>
    </p><p>06.01.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5626">filips203: Lackova 996</a> założona przez <a href="viewprofile.php?userid=49">filips</a>
    </p><p>17.08.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4527">Spissky Hrad</a> założona przez <a href="viewprofile.php?userid=1809">mkoooza</a>
    </p><p>13.07.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4135">Muzeum Oravskej Dediny</a> założona przez <a href="viewprofile.php?userid=943">Pavel224</a>
    </p><p>12.07.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4123">Kąpielisko Oravice</a> założona przez <a href="viewprofile.php?userid=716">pfabi</a>
    </p><p>26.02.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=2846">Orawski Biały Potok</a> założona przez <a href="viewprofile.php?userid=65">Caches_Hunters</a>
    </p><p>17.02.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=2787">&quot;niebo ....&quot; </a> założona przez <a href="viewprofile.php?userid=1613">R62</a>
    </p><p>23.09.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=1959">Gruszki na Wierzbie</a> założona przez <a href="viewprofile.php?userid=433">bogobig</a>
    </p><p>27.07.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=1441">Droga na Rysy</a> założona przez <a href="viewprofile.php?userid=123">Redbox-PL</a>
    </p><p>09.04.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=618">Góralska Chata</a> założona przez <a href="viewprofile.php?userid=315">GeoCrak Team</a>
    </p><p class="content-title-noshade-size3">Thailand</p><p>23.11.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=8650">Phuket Town Park</a> założona przez <a href="viewprofile.php?userid=3531">olo_kolo_Team</a>
    </p><p>16.11.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=8603">Gold Mount</a> założona przez <a href="viewprofile.php?userid=3531">olo_kolo_Team</a>
    </p><p>04.11.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=8508">Wat Suthat and the Giant Swing</a> założona przez <a href="viewprofile.php?userid=3531">olo_kolo_Team</a>
    </p><p>08.10.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=8321">New world house</a> założona przez <a href="viewprofile.php?userid=3531">olo_kolo_Team</a>
    </p><p class="content-title-noshade-size3">Tunesien</p><p>09.10.2008 - <img src="tpl/stdstyle/images/cache/16x16-quiz.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=5038">Gammadion, Fylfot czy słowiańska Swarzyca...?</a> założona przez <a href="viewprofile.php?userid=58">Saracen</a>
    </p><p>15.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4871">Mos Espa, Tatooine Planet</a> założona przez <a href="viewprofile.php?userid=801">PatrykG</a>
    </p><p class="content-title-noshade-size3">Turcja</p><p>14.10.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=2119">Rafting</a> założona przez <a href="viewprofile.php?userid=315">GeoCrak Team</a>
    </p><p>14.10.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=2118">Coś dla ochłody</a> założona przez <a href="viewprofile.php?userid=315">GeoCrak Team</a>
    </p><p>14.09.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=1867">Budowla niejedna w centrum</a> założona przez <a href="viewprofile.php?userid=315">GeoCrak Team</a>
    </p><p>14.09.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=1866">Pomnik w Side</a> założona przez <a href="viewprofile.php?userid=315">GeoCrak Team</a>
    </p><p>07.08.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=731">Turecki Manavgat</a> założona przez <a href="viewprofile.php?userid=315">GeoCrak Team</a>
    </p><p class="content-title-noshade-size3">USA</p><p>27.06.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3998">Mulholland Drive</a> założona przez <a href="viewprofile.php?userid=1297">QUINTO</a>
    </p><p class="content-title-noshade-size3">Ukraina</p><p>07.10.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=8310">Wędrówka pasmem Czarnohory - #1 Wędrowników</a> założona przez <a href="viewprofile.php?userid=15180">wedrownicy</a>
    </p><p>14.06.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7065">Tylko dla Stalkerów</a> założona przez <a href="viewprofile.php?userid=32">Doczu</a>
    </p><p>20.05.2009 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6712">Powrót do przeszłości - Lviv</a> założona przez <a href="viewprofile.php?userid=58">Saracen</a>
    </p><p>03.04.2009 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6133">G21 - &quot;Przełęcz Legionów&quot;</a> założona przez <a href="viewprofile.php?userid=7214">Giovanni</a>
    </p><p>02.04.2009 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6128">G20 - &quot;Biały Słoń&quot;</a> założona przez <a href="viewprofile.php?userid=7214">Giovanni</a>
    </p><p>22.03.2009 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6037">G15- Pod Kamieniem,pod Podolskim stoi Turek ze swym wojskiem</a> założona przez <a href="viewprofile.php?userid=7214">Giovanni</a>
    </p><p>02.10.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=2027">Tam gdzie czas zatrzymał się w 1986 roku</a> założona przez <a href="viewprofile.php?userid=1092">zabayek</a>
    </p><p>09.12.2006 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=244">Kazantyp</a> założona przez <a href="viewprofile.php?userid=265">adam</a>
    </p><p>09.12.2006 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=243">Czufut-Kale</a> założona przez <a href="viewprofile.php?userid=265">adam</a>
    </p><p>09.12.2006 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=242">Czatyr-Dag</a> założona przez <a href="viewprofile.php?userid=265">adam</a>
    </p><p class="content-title-noshade-size3">United Arab Emirates</p><p>06.04.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=6171">Dubai Dream</a> założona przez <a href="viewprofile.php?userid=319">Mela</a>
    </p><p class="content-title-noshade-size3">Wielka Brytania</p><p>09.11.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=8549">The  Hoe -  Plymouth</a> założona przez <a href="viewprofile.php?userid=13799">teuszp</a>
    </p><p>17.06.2008 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=3897">ZYR 156 - Hay's Wharf</a> założona przez <a href="viewprofile.php?userid=449">ZYR</a>
    </p><p>09.10.2007 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=2088">Hyde Park</a> założona przez <a href="viewprofile.php?userid=315">GeoCrak Team</a>
    </p><p>09.10.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=2086">Hispaniola</a> założona przez <a href="viewprofile.php?userid=315">GeoCrak Team</a>
    </p><p>09.10.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=2085">Delikatesy Worcester Park</a> założona przez <a href="viewprofile.php?userid=315">GeoCrak Team</a>
    </p><p>30.08.2007 - <img src="tpl/stdstyle/images/cache/16x16-virtual.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=1754">0°0'00&quot;</a> założona przez <a href="viewprofile.php?userid=61">darkmoor</a>
    </p><p class="content-title-noshade-size3">Włochy</p><p>22.06.2009 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=7168">veni vidi</a> założona przez <a href="viewprofile.php?userid=8575">lepti</a>
    </p><p>05.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4767">Forte Sperone - Genova</a> założona przez <a href="viewprofile.php?userid=3718">Tusial.</a>
    </p><p>01.09.2008 - <img src="tpl/stdstyle/images/cache/16x16-traditional.png" border="0" width="16" height="16" alt="Cache" title="Cache"/><a href="viewcache.php?cacheid=4722">Stazione Genova-Nervi</a> założona przez <a href="viewprofile.php?userid=3718">Tusial.</a>
    </p></div>