INSERT INTO `cache_attrib` (`id`, `language`, `text_short`, `text_long`, `icon_large`, `icon_no`, `icon_undef`, `category`, `default`) VALUES
(1, 'SV', 'Night', 'Only at night', 'images/attributes/night.png', 'images/attributes/night-no.png', 'images/attributes/night-disabled.png', 6, 0),
(6, 'SV', 'OC Only', 'Listed on Opencaching only', 'images/attributes/oconly.png', 'images/attributes/oconly-no.png', 'images/attributes/oconly-disabled.png', 8, 0),
(8, 'SV', 'letter', 'Letterbox - stamp required', 'images/attributes/letter.png', 'images/attributes/letter-no.png', 'images/attributes/letter-disabled.png', 4, 0),
(9, 'SV', 'danger', 'Dangerous territory', 'images/attributes/danger.png', 'images/attributes/danger-no.png', 'images/attributes/danger-disabled.png', 1, 0),
(10, 'SV', 'train', 'Active rail lines nearby', 'images/attributes/train.png', 'images/attributes/train-no.png', 'images/attributes/train-disabled.png', 1, 0),
(11, 'SV', 'cliff', 'Cliffs / rocks', 'images/attributes/cliff.png', 'images/attributes/cliff-no.png', 'images/attributes/cliff-disabled.png', 1, 0),
(12, 'SV', 'hunting', 'Hunting', 'images/attributes/hunting.png', 'images/attributes/hunting-no.png', 'images/attributes/hunting-disabled.png', 1, 0),
(13, 'SV', 'thorn', 'Thorn', 'images/attributes/thorn.png', 'images/attributes/thorn-no.png', 'images/attributes/thorn-disabled.png', 1, 0),
(14, 'SV', 'ticks', 'Ticks', 'images/attributes/ticks.png', 'images/attributes/ticks-no.png', 'images/attributes/ticks-disabled.png', 1, 0),
(15, 'SV', 'mine', 'The cache leads to a (former) mining region', 'images/attributes/mine.png', 'images/attributes/mine-no.png', 'images/attributes/mine-disabled.png', 1, 0),
(16, 'SV', 'plants', 'Poisonous Plants', 'images/attributes/plants.png', 'images/attributes/plants-no.png', 'images/attributes/plants-disabled.png', 1, 0),
(17, 'SV', 'animals', 'Toxic / dangerous animals', 'images/attributes/animals.png', 'images/attributes/animals-no.png', 'images/attributes/animals-disabled.png', 1, 0),
(18, 'SV', 'parking', 'Parking nearby', 'images/attributes/parking.png', 'images/attributes/parking-no.png', 'images/attributes/parking-disabled.png', 2, 0),
(19, 'SV', 'public', 'Accessible by public transport', 'images/attributes/public.png', 'images/attributes/public-no.png', 'images/attributes/public-disabled.png', 2, 0),
(20, 'SV', 'water', 'Drinking water in the area', 'images/attributes/water.png', 'images/attributes/water-no.png', 'images/attributes/water-disabled.png', 2, 0),
(21, 'SV', 'restrooms', 'Public toilets nearby', 'images/attributes/restrooms.png', 'images/attributes/restrooms-no.png', 'images/attributes/restrooms-disabled.png', 2, 0),
(22, 'SV', 'phone', 'Phone nearby', 'images/attributes/phone.png', 'images/attributes/phone-no.png', 'images/attributes/phone-disabled.png', 2, 0),
(23, 'SV', 'firstaid', 'First aid available', 'images/attributes/firstaid.png', 'images/attributes/firstaid-no.png', 'images/attributes/firstaid-disabled.png', 2, 0),
(24, 'SV', 'car', 'Near By car', 'images/attributes/car.png', 'images/attributes/car-no.png', 'images/attributes/car-disabled.png', 3, 0),
(25, 'SV', 'hiking', 'Longer hike', 'images/attributes/hiking.png', 'images/attributes/hiking-no.png', 'images/attributes/hiking-disabled.png', 3, 0),
(26, 'SV', 'wading', 'Boggy / muddy terrain', 'images/attributes/wading.png', 'images/attributes/wading-no.png', 'images/attributes/wading-disabled.png', 3, 0),
(27, 'SV', 'steep', 'Hilly Terrain', 'images/attributes/steep.png', 'images/attributes/steep-no.png', 'images/attributes/steep-disabled.png', 3, 0),
(28, 'SV', 'climbing', 'Lightweight Climbing - without equipment', 'images/attributes/climbing.png', 'images/attributes/climbing-no.png', 'images/attributes/climbing-disabled.png', 3, 0),
(29, 'SV', 'swimming', 'Swimming required', 'images/attributes/swimming.png', 'images/attributes/swimming-no.png', 'images/attributes/swimming-disabled.png', 3, 0),
(30, 'SV', 'interestsign', 'Interesting place', 'images/attributes/interestsign.png', 'images/attributes/interestsign-no.png', 'images/attributes/interestsign-disabled.png', 4, 0),
(31, 'SV', 'moving', 'Moving Target', 'images/attributes/moving.png', 'images/attributes/moving-no.png', 'images/attributes/moving-disabled.png', 4, 0),
(32, 'SV', 'webcam', 'Webcam ', 'images/attributes/webcam.png', 'images/attributes/webcam-no.png', 'images/attributes/webcam-disabled.png', 4, 0),
(33, 'SV', 'indoor', 'In closed spaces', 'images/attributes/indoor.png', 'images/attributes/indoor-no.png', 'images/attributes/indoor-disabled.png', 4, 0),
(34, 'SV', 'submerged', 'In the water', 'images/attributes/submerged.png', 'images/attributes/submerged-no.png', 'images/attributes/submerged-disabled.png', 4, 0),
(35, 'SV', 'nogps', 'No GPS', 'images/attributes/nogps.png', 'images/attributes/nogps-no.png', 'images/attributes/nogps-disabled.png', 4, 0),
(36, 'SV', 'fee', 'Access or parking fee', 'images/attributes/fee.png', 'images/attributes/fee-no.png', 'images/attributes/fee-disabled.png', 5, 0),
(37, 'SV', 'overnight', 'Accommodation Required', 'images/attributes/overnight.png', 'images/attributes/overnight-no.png', 'images/attributes/overnight-disabled.png', 5, 0),
(38, 'SV', 'available', 'Around the clock', 'images/attributes/available.png', 'images/attributes/available-no.png', 'images/attributes/available-disabled.png', 6, 0),
(39, 'SV', 'time', 'At certain seasons', 'images/attributes/time.png', 'images/attributes/time-no.png', 'images/attributes/time-disabled.png', 6, 0),
(40, 'SV', 'day', 'Only daytime', 'images/attributes/day.png', 'images/attributes/day-no.png', 'images/attributes/day-disabled.png', 6, 0),
(41, 'SV', 'tide', 'Tides', 'images/attributes/tide.png', 'images/attributes/tide-no.png', 'images/attributes/tide-disabled.png', 6, 0),
(42, 'SV', 'date', 'All year round Access', 'images/attributes/date.png', 'images/attributes/date-no.png', 'images/attributes/date-disabled.png', 7, 0),
(43, 'SV', 'Nature', 'Nature', 'images/attributes/naturschutz.png', 'images/attributes/naturschutz-no.png', 'images/attributes/naturschutz-disabled.png', 7, 0),
(44, 'SV', 'snow', 'Winter safe', 'images/attributes/snow.png', 'images/attributes/snow-no.png', 'images/attributes/snow-disabled.png', 7, 0),
(46, 'SV', 'tools', 'Special Equipment', 'images/attributes/tools.png', 'images/attributes/tools-no.png', 'images/attributes/tools-disabled.png', 9, 0),
(47, 'SV', 'compass', 'Compass', 'images/attributes/compass.png', 'images/attributes/compass-no.png', 'images/attributes/compass-disabled.png', 9, 0),
(48, 'SV', 'flashlight', 'flashlight', 'images/attributes/flashlight.png', 'images/attributes/flashlight-no.png', 'images/attributes/flashlight-disabled.png', 9, 0),
(49, 'SV', 'rappeling', 'Rappeling', 'images/attributes/rappeling.png', 'images/attributes/rappeling-no.png', 'images/attributes/rappeling-disabled.png', 9, 0),
(50, 'SV', 'cave', 'Cave', 'images/attributes/cave.png', 'images/attributes/cave-no.png', 'images/attributes/cave-disabled.png', 9, 0),
(51, 'SV', 'scuba', 'Scuba', 'images/attributes/scuba.png', 'images/attributes/scuba-no.png', 'images/attributes/scuba-disabled.png', 9, 0),
(52, 'SV', 'boat', 'Boat', 'images/attributes/boat.png', 'images/attributes/boat-no.png', 'images/attributes/boat-disabled.png', 9, 0),
(53, 'SV', 'aircraft', 'Aircraft', 'images/attributes/aircraft.png', 'images/attributes/aircraft-no.png', 'images/attributes/aircraft-disabled.png', 9, 0),
(54, 'SV', 'wiki', 'Wiki', 'images/attributes/wiki.png', 'images/attributes/wiki-no.png', 'images/attributes/wiki-disabled.png', 10, 0),
(55, 'SV', 'riddle', 'Riddle', 'images/attributes/riddle.png', 'images/attributes/riddle-no.png', 'images/attributes/riddle-disabled.png', 10, 0),
(56, 'SV', 'arith_prob', 'Arith prob', 'images/attributes/arith_prob.png', 'images/attributes/arith_prob-no.png', 'images/attributes/arith_prob-disabled.png', 10, 0),
(57, 'SV', 'othercache', 'Other cache', 'images/attributes/othercache.png', 'images/attributes/othercache-no.png', 'images/attributes/othercache-disabled.png', 10, 0),
(58, 'SV', 'ask', 'Starting conditions', 'images/attributes/ask.png', 'images/attributes/ask-no.png', 'images/attributes/ask-disabled.png', 10, 0),
(59, 'SV', 'kids', 'Kids', 'images/attributes/kids.png', 'images/attributes/kids-no.png', 'images/attributes/kids-disabled.png', 11, 0);