name: Style

on:
  push:
  pull_request:

jobs:
  php:
    name: PHP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: PHP-CS-Fixer cache
        uses: actions/cache@v4
        with:
          path: .php-cs-fixer.cache
          key: php-cs-fixer-${{ github.sha }}
          restore-keys: php-cs-fixer-

      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix --dry-run --diff
